export const FETCH_ALL_MOVIES_REQUESTED = 'FETCH_ALL_MOVIES_REQUESTED'
export const FETCH_ALL_MOVIES_SUCCESSED = 'FETCH_ALL_MOVIES_SUCCESSED'
export const FETCH_ALL_MOVIES_FAILED = 'FETCH_ALL_MOVIES_FAILED'